substitutions:
  device_name: switch01
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt: !secret mqtt

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

# # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#   ssid: "Switch01 Fallback Hotspot"
#   password: "RUdKSgId4pTe"

# Enable Fallback Web Interface
#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:


mqtt:
  broker: ${mqtt}
  port: 1883
  reboot_timeout: 0s

http_request:


sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: gpio12
    name: "oben-links"
    pin: GPIO12
    on_multi_click:
    - timing:
         - ON for 50ms to 500ms
         - OFF for 50ms to 500ms
         - ON for 50ms to 500ms
         - OFF for at least 50ms
      then:
        - logger.log: "oben-links DOUBLE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/DOUBLE
            payload: "DOUBLE"
        - http_request.post: http://192.168.89.122/light/0?turn=on&brightness=100&transition=5000
    - timing:
         - ON for at least 500ms
      then:
        - logger.log: "oben-links LONG-HOLD"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/HOLD
            payload: "HOLD"
        - http_request.post: http://192.168.89.122/light/0?dim=up
    - timing:
        - ON for at least 500ms
        - OFF for at least 50ms
      then:
        - logger.log: "oben-links LONG-RELEASE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/RELEASE
            payload: "RELEASE"
        - http_request.post: http://192.168.89.122/light/0?dim=stop
    - timing:
         - ON for at most 500ms
         - OFF for at least 500ms
      then:
        - logger.log: "oben-links SHORT"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-links/SHORT
            payload: "SHORT"
        - http_request.post: http://192.168.89.122/light/0?turn=toggle

  - platform: gpio
    id: gpio13
    name: "unten-links"
    pin: GPIO13
    on_multi_click:
    - timing:
         - ON for 50ms to 500ms
         - OFF for 50ms to 500ms
         - ON for 50ms to 500ms
         - OFF for at least 50ms
      then:
        - logger.log: "unten-links DOUBLE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/DOUBLE
            payload: "DOUBLE"
        - http_request.post: http://192.168.89.122/light/0?turn=on&brightness=50&transition=5000
    - timing:
         - ON for at least 500ms
      then:
        - logger.log: "unten-links LONG-HOLD"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/HOLD
            payload: "HOLD"
        - http_request.post: http://192.168.89.122/light/0?dim=down
    - timing:
        - ON for at least 500ms
        - OFF for at least 50ms
      then:
        - logger.log: "unten-links LONG-RELEASE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/RELEASE
            payload: "RELEASE"
        - http_request.post: http://192.168.89.122/light/0?dim=stop
    - timing:
         - ON for at most 500ms
         - OFF for at least 500ms
      then:
        - logger.log: "unten-links SHORT"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-links/SHORT
            payload: "SHORT"
        - http_request.post: http://192.168.89.122/light/0?turn=off


  - platform: gpio
    id: gpio16
    name: "oben-rechts"
    pin: GPIO16
    on_multi_click:
    - timing:
         - ON for 50ms to 500ms
         - OFF for 50ms to 500ms
         - ON for 50ms to 500ms
         - OFF for at least 50ms
      then:
        - logger.log: "oben-rechts DOUBLE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-rechts/DOUBLE
            payload: "DOUBLE"
    - timing:
         - ON for at least 500ms
      then:
        - logger.log: "oben-rechts LONG-HOLD"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-rechts/HOLD
            payload: "HOLD"
    - timing:
        - ON for at least 500ms
        - OFF for at least 50ms
      then:
        - logger.log: "oben-rechts LONG-RELEASE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-rechts/RELEASE
            payload: "RELEASE"
    - timing:
         - ON for at most 500ms
         - OFF for at least 500ms
      then:
        - logger.log: "oben-rechts SHORT"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/oben-rechts/SHORT
            payload: "SHORT"
        - http_request.post: http://192.168.89.121/relay/0?turn=toggle


  - platform: gpio
    id: gpio14
    name: "unten-rechts"
    pin: GPIO14
    on_multi_click:
    - timing:
         - ON for 50ms to 500ms
         - OFF for 50ms to 500ms
         - ON for 50ms to 500ms
         - OFF for at least 50ms
      then:
        - logger.log: "unten-rechts DOUBLE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-rechts/DOUBLE
            payload: "DOUBLE"
    - timing:
         - ON for at least 500ms
      then:
        - logger.log: "unten-rechts LONG-HOLD"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-rechts/HOLD
            payload: "HOLD"
    - timing:
        - ON for at least 500ms
        - OFF for at least 50ms
      then:
        - logger.log: "unten-rechts LONG-RELEASE"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-rechts/RELEASE
            payload: "RELEASE"
    - timing:
         - ON for at most 500ms
         - OFF for at least 500ms
      then:
        - logger.log: "unten-rechts SHORT"
        - mqtt.publish:
            topic: ${device_name}/binary_sensor/unten-rechts/SHORT
            payload: "SHORT"
        - http_request.post: http://192.168.89.121/relay/0?turn=off
        
